# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# avoid duplicate tests in PRs
branches:
  only:
    - master
os:
  - linux
  # - osx
julia:
  - 1
#  - nightly
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
      - stage: "Documentation"
        julia: 1.5
        os: linux
        script:
            - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                                   Pkg.instantiate()'
            - julia --project=docs/ docs/make.jl
        after_success: skip
